### ISSUE TITLE
Merge into another implementation of Gruvbox

### ISSUE THREAD

**Issue by greduan** [martijnat/nubox#2]
Hey, I'm an old maintainer for [emacs-theme-gruvbox](https://github.com/greduan/emacs-theme-gruvbox), however I still "own" the repo in GitHub. So that is to say, I'm just suggesting something, I probably won't actually do anything about/with it.

My question was about, do you think your changes could be merged into my/our version of the theme? Assuming there are things to be merged of course.

Right now there are like 4 different versions of Gruvbox for Emacs, and I think it's a better idea to concentrate on one version.

In any case, just putting this out there. I don't use Emacs currently so I'm only a holder/maintainer of the repo. :)

**Comment by martijnat** [comment]
This theme is not created by modifying an existing gruvbox theme, so merging is not trivial. I actually have simplified the scheme (for instance this theme does not have orange) and changed at least one color.

Some changes which could be reasonably easily added to the emacs-theme-gruvbox
- Fix for ansi-term colors
- Additional faces

Looking at the code from your repository It might be possible to add an option for a light theme, just like you use the gruvbox-contrast variable.

Finally what is the status of the license of your repository? [Here you discuss the idea of re licensing under GPL3](https://github.com/greduan/emacs-theme-gruvbox/issues/58), and seemed to come to an agreement yet nothing seems to have changed.

**Comment by greduan** [comment]
/cc @jasonm23

@martijnat 

If I remember correctly, Jason was playing with a light version but didn't come to a satisfying solution. https://github.com/greduan/emacs-theme-gruvbox/issues/45

As for the license, indeed a decision was reached it seems. I can do it myself just need to discuss with Jason how the new copyright statements should look.
